name: Publish CLI
# Note: Version bumping is now manual. Update cli/package.json version before pushing to main.
on:
  push:
    branches: [main]

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:cli

      - name: Check npm authentication
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Get current version
        id: current_version
        run: |
          cd cli
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          
      - name: Create tag for current version
        run: |
          git tag "v${{ steps.current_version.outputs.version }}" || true
          git push origin "v${{ steps.current_version.outputs.version }}" || true

      - name: Publish to npm
        run: |
          cd cli
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.current_version.outputs.version }}
          release_name: CLI v${{ steps.current_version.outputs.version }}
          body: |
            ## XSwarm CLI v${{ steps.current_version.outputs.version }}

            ### Installation
            ```bash
            npm install -g xswarm@${{ steps.current_version.outputs.version }}
            # or
            npx xswarm@${{ steps.current_version.outputs.version }}
            ```

            ### Changes
            See [commit history](https://github.com/${{ github.repository }}/commits/v${{ steps.current_version.outputs.version }}) for details.
          draft: false
          prerelease: false
